// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfghsvdgwxbztgbevesd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZ2hzdmRnd3hienRnYmV2ZXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzY5MjksImV4cCI6MjA3NDA1MjkyOX0.Fj3hCM6-_nq83mU3dMZmRzHOF29lIDKBUNA1ryurOSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});